#!/bin/sh

grep -q "^dtparam=i2c_arm=on" /boot/config.txt || \
	echo "dtparam=i2c_arm=on" >> /boot/config.txt

modprobe i2c-dev 2>/dev/null
modprobe i2c-bcm2835 2>/dev/null
modprobe i2c-brcmstb 2>/dev/null

# Rebuild opkg config
cat > /etc/opkg.conf <<'EOF'
dest root /
dest ram /tmp
lists_dir ext /var/opkg-lists
option overlay_root /overlay
EOF

exit 0
