#!/bin/sh

cat > /boot/config.txt <<'EOF'
include distroconfig.txt

[pi2]
dtparam=i2c_arm=on,audio=on

[pi3]
dtparam=i2c_arm=on,audio=on

[pi4]
dtparam=i2c_arm=on,audio=on

[all]
dtparam=i2c_arm=on
EOF

modprobe i2c-dev 2>/dev/null
modprobe i2c-bcm2835 2>/dev/null
modprobe i2c-brcmstb 2>/dev/null

cat > /etc/opkg.conf <<'EOF'
dest root /
dest ram /tmp
lists_dir ext /var/opkg-lists
option overlay_root /overlay
EOF

exit 0
